[project]
name = "myfirstnewproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ensure>=1.0.4",
    "joblib>=1.5.3",
    "pathlib>=1.0.1",
    "python-box>=7.3.2",
    "pandas",
    "ipykernel>=7.1.0",
]
